### ISSUE TITLE
Player join issue

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#10]
Hey jolbol1,

A developer just let me know that RandomTeleport is fetching the latest plugin version from an URL everytime a player joins, whether the player is OP or not. When lots of players login, the plugin will show up high in timings.

Something that can be done?

Thanks.

**Comment by jolbol1** [comment]
I noticed that yesterday It was a stupid way for me to do it, Sorry. It has been changed for the current version in testing, As well as a complete overhaul of the coordinate system itself.

**Comment by Sikatsu** [comment]
Nice, thanks!

**Comment by jolbol1** [comment]
Just uploaded a new update which changes this. Furthermore it has the new coordinates manager.
