### ISSUE TITLE
Error Eccured: /rc wand

### ISSUE THREAD

**Issue by whiteghost3000** [jolbol1/RandomCoordinatesV2#14]
This is a reply to what you said:
Here is what the console spits out whevener I do /rc wand.
https://pastebin.com/MVdnTDpg

-- Thanks
whiteghost3000

**Comment by jolbol1** [comment]
On holiday at the moment, but it appears this is due to a spigot bukkit mismatch. I assume you are on bukkit?

**Comment by whiteghost3000** [comment]
Oh ok sorry for interrupting you... But I am using Bukkit and it looks like it could be a really good plugin. Is it only for Spigot?

-- Thanks
whiteghost3000

**Comment by jolbol1** [comment]
Its not supposed to be only for spigot, Ive made an accident with one of the imports and made it import from spigot, not bukkit. Will be an easy fix!

**Comment by whiteghost3000** [comment]
So do I redownload or could you please explain what I do? Im new to these things thanks!

-- Thanks
whiteghost3000

**Comment by jolbol1** [comment]
It's completely on my side at the moment sorry, Will be the first thing I do when I get back!

Please be patient and wait for the update :)

**Comment by whiteghost3000** [comment]
Ok. Have a nice time!

-- Thanks
whiteghost3000

**Comment by jolbol1** [comment]
Now fixed, Thanks for waiting.
