### ISSUE TITLE
Teleport in Ocean Biome

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#15]
Using /rtp sometimes ends up in an Ocean biome. Many players don't like this, something that can be changed?

**Comment by jolbol1** [comment]
Hi, Currently on holiday. This was reported on spigot and will be fixed as soon as I get back. It appears a fix is to switch back to the old code, by turning experimental to false.

**Comment by Sikatsu** [comment]
Thanks for your reply. Waiting for the update.

**Comment by jolbol1** [comment]
Fixed, Sorry for the delay and the issue itself.
