### ISSUE TITLE
Teleports players in void on SkyGrid map

### ISSUE THREAD

**Issue by Roadhog360** [jolbol1/RandomCoordinatesV2#16]
Making the world SkyGrid causes players to be teleported into the void most of the time. Please add a check that avoids the void.

**Comment by jolbol1** [comment]
The issue here I believe is that you are using a custom generator. There is no easy lag free way to check the custom generation, so it treats it as a vanilla world. This leads to the plugin thinking that there is a block there, As there would be in default. The only way I saw to counter this was to add the SkyBlock option, [Seen here in the Wiki.](https://github.com/jolbol1/RandomCoordinatesV2/wiki/SkyBlock)

If you have any improvements that could be made to this please let me know. Furthermore, If what's described above isnt the issue you are referring to please let me know, And I'll work on a fix tomorrow. (Day I get back from Holiday).

**Comment by Roadhog360** [comment]
This is a custom generator, yes. 
I don't think activating the Skyblock option would work, so here's my issue in more detail.
The world looks like this.
https://gyazo.com/bbc31fa3e92496140a9a30f30fab38ef
The issue is players don't always get teleported on top of a block.
Your RandomTP looks like the only usable one I have, so could you make a way to fix this?
Here's my suggestion: You could make it so the player is either always teleported on top of a block, or make it so you can set a minimum y axis. If the ground is below the y axis, it puts a glass block below the player. So that way, I could set the minimum y to 128, so instead of teleporting me above the void, I get put at ground level with a glass block below me.

**Comment by jolbol1** [comment]
Was similar to what I expected. As I stated before I can't check for if the blocks safe when using custom generators and new chunks. Its should be working in pre-generated chunks.

I'm going to add a custom option in the next update that adds a default Y value for SkyBlock worlds.

**Comment by jolbol1** [comment]
Added a DeafultY option as of version 0.5.4-Release.

This is the Y value of the block that will be placed, and player teleported to.

**Comment by Roadhog360** [comment]
Cool. It actually IS possible to check if the block is safe because my current plugin always teleports you to a safe location on the grid (Even though the plugin is really bad so I want to use yours).
BTW, just thought of another suggestion to make this world Random Teleport compatible. How about an option to make a random chunk load, and then teleporting a player in it? This way, the plugin can generate the world and know where the player is safe to go without any glass blocks. Sorry, didn't think of this before.
Also, how do I make a sign.

**Comment by jolbol1** [comment]
My plugin should be able to check if the location is safe for already pre-generated chunks, But I will look further into a way to get round this. Lots of issue I have with the pre gen of chunks is lag. Even loading one or two seems to be causing lag. 

You have raised an insane amount of good suggestions and I will look into them. Sadly, I wont be able to devote as much time as normal as I have exams coming up soon which takes up around a month of my life from here on out. During this period however, I will look into and test out some methods and some of the features you have suggested, and see if it can be easily done.

Lastly, The teleport cancelled message bug I will look into tonight, Thank you for raising the issue, and sorry it wasn't fixed pre-release.

**Comment by jolbol1** [comment]
Also, As for making a sign, That is covered here in the wiki 
https://github.com/jolbol1/RandomCoordinatesV2/wiki/Signs#how

All you have to do is place a sign and write [RandomCoords].

Furthermore, Signs do allow you to specify custom world to teleport to. At the moment however there is no feature to set a default world for the command. You have raised an interesting suggestion and I will look into it.

**Comment by Roadhog360** [comment]
Also, just remembered that I have no teleport delay, so the cancel bug makes even less sense.

**Comment by jolbol1** [comment]
Was looking into this some more before I made the update. Managed to work out that my first thoughts were wrong. My plugin is able to tell what block it is under custom generation. The issue is, It see's air as safe. Adding AIR to the blacklist seems to work just fine.

**Comment by Roadhog360** [comment]
Sorry for late reply, my server went down when I stopped replying and I forgot to mention this.
I have a server again... and after downloading the plugin, any RTP causes a 3 second lag spike.
Is there any way to fix it? I don't think it did this before.
