### ISSUE TITLE
Random Teleport sometimes killing players

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#17]
Hey,

I'm getting some reports that players who use /rtp end up in the air falling to their dead.

Experimental is set to false due to the other bug.

**Comment by jolbol1** [comment]
Hmm this is really odd. I have one theory as to why it's happening and am looking into a fix now. 

Update coming soon.

**Comment by jolbol1** [comment]
I believe I've fixed the issue, But oddly I found this bug in the experimental not old. Looking into a fix now.

The experimental however should work now with the latest update
