### ISSUE TITLE
RandomTP is not working ''You don't have 0.0 required for this!''

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#2]
Hey jolbol1,

I'm trying to use this plugin, however it keeps saying ''You don't have 0.0 required for this!'' even while I do have a balance. I have both vault and essentialsX installed.

Hope this can be fixed somehow, because I finally found a RandomTP system with Portals AND Worldborder support :)

Thanks in advance.

**Comment by Sikatsu** [comment]
Now that I rollbacked from the beta, this seems to work.

However, now I can't teleport because he can't find a save location to teleport too. How can I fix this lol? World is big enough o.O

http://prntscr.com/e3xpzs

**Comment by jolbol1** [comment]
I can see where the charge error is coming from in the beta and was an oversight by me. My next question is could I see your config? Im unsure as to why it can't find a safe place to teleport. If I cannot work out the error from here I can always attempt to add some debug messages to see where my plugin is getting stuck.

Sorry for the bad experience with this plugin so far!

**Comment by Sikatsu** [comment]
When I rollbacked the version, I noticed that when it's set to 0 in config, the teleport works fine. But when I set it to for example 5, it says I don't have 5.0, even while I do.

This is the config: http://pastebin.com/qRL62NZs

When I extend the worldborder, it seems to work fine though. Not sure why it didn't work when the worldborder was set to 1k.

No problem! Love the plugin, glad I found it and that it's still being updated. ^^

**Comment by jolbol1** [comment]
I assume you have [Vault](https://dev.bukkit.org/projects/vault) installed? The rest I struggle to debug as there is no console output, but I will look into it now. Thank you.

**Comment by jolbol1** [comment]
I've fixed the cost problem as for the no safe teleport reason I'm unsure as to why this is happening when the world border is small. In the latest release version, I did modify the WorldBorder function to work properly And did an insane amount of testing. 

Expect an update soon :)
The most I can do, and what I will do is in the next release version add some debug messages to further help people with issues such as yours.

**Comment by Sikatsu** [comment]
I indeed have vault installed. :)

Ah, awesome. I will test it's functionality this weekend/monday when it goes live on my server. If the players report anything buggy, I will let you know here. ^^

Thanks, waiting the update!

**Comment by jolbol1** [comment]
Posted the update to Bukkit, Just waiting for the review now.

**Comment by Sikatsu** [comment]
I will let you know once I have it live on my server. :)
