### ISSUE TITLE
/rc warp not working as it should

### ISSUE THREAD

**Issue by FrankHeijden** [jolbol1/RandomCoordinatesV2#22]
- [x] 1.11+
- [ ] 1.10+
- [ ] 1.9+
- [ ] 1.8 +
- [ ] 1.7+

## Issue Description
/rc warp -> does tp to the warp but on top of every other blocks. So when i have set a warp underground or under a tree it will spawn me on top of the tree with /rc warp.

## Reproduce Steps
exactly as above.

## Additional Information

**Comment by jolbol1** [comment]
Should be an easy fix, Looking into it cheers.

**Comment by jolbol1** [comment]
Fixed in the latest update, Thanks for the report 👍
