### ISSUE TITLE
RandomORG not working

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#3]
Hey,

When trying to use RandomORG I receive this error: http://pastebin.com/6xftGFwD

**Comment by jolbol1** [comment]
Is this using the beta, Normal or both? From the error that's returned there, I can see that for some reason it just cant connect to the site and get the coordinate from it. This is odd considering that no code has been changed in this part since it was made, and works on my end.

**Comment by Sikatsu** [comment]
This is after I rollbacked from the beta. Not sure why it doesn't work though.
