### ISSUE TITLE
Coordinates green color is hardcoded

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#4]
I wanted to change the coordinates to dark aqua, but it seems the color is hardcoded.

TeleportMessage: '&7Je bent geteleporteert naar &3%coordinates&7!'

**Comment by jolbol1** [comment]
Thanks for this, Wil fix in update before friday.

**Comment by jolbol1** [comment]
Changed in next version.

**Comment by Sikatsu** [comment]
Thanks!
