### ISSUE TITLE
RandomCoords lagging, maybe?

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#6]
I added RandomCoords to my server today and ever since the server contains lagg spikes. Nothing else has changed in the past month, however. Might RandomCoords be causing those spikes when someone uses /rtp ?

**Comment by jolbol1** [comment]
Timings may be able to help you/me see what the issue is here? Could you post them?

**Comment by Sikatsu** [comment]
I believe they don't say anything about this plugin. https://timings.spigotmc.org/?url=casodusate

**Comment by jolbol1** [comment]
From that it would appear that my plugin is running smoothly.

**Comment by Sikatsu** [comment]
Was thinking the same, didn't do timings on the time of the report. But since it are lagg spikes which never really occured before, I thought it maybe occured when someone uses /rtp.

**Comment by jolbol1** [comment]
Maybe run timings for a bit longer while the lag spikes are occurring and I can see if it's my plugin and diagnose from there.

**Comment by Sikatsu** [comment]
The current timings I sent contained a lagg spike of around 15 seconds. I will check next time. Thanks!

**Comment by jolbol1** [comment]
From those timings I can tell you there is a lot of entity lag, Which won't be from my plugin seems to be world2?

**Comment by Sikatsu** [comment]
Entities are quite nerfed using React, actually. So much that is impacts gameplay too. But this has always been showing up in my timings and those lagg spikes are new since yesterday.
