### ISSUE TITLE
Custom prefix not working

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#8]
Prefix: '&3[VillagerCraft] '

http://prntscr.com/ejtcuc

**Comment by jolbol1** [comment]
I just discovered this bug in a similar way. 

Due to the way the messages class is set up the prefix is set onEnable, thus changing it in languages.yml won't change the prefix until a server reload or restart.

If you are able to restart or reload it should work.

 I'm looking into this now.

**Comment by Sikatsu** [comment]
Currently I can't restart/reload the server unfortunatly. Usually prefix can be changed by plugin reload command?

**Comment by jolbol1** [comment]
Yes the problem was that I hard coded it originally into the onEnable, I've just pushed v0.1.1 to Bukkit with a fix for this.

Sorry this was overlooked.

**Comment by Sikatsu** [comment]
Ahh, alright! Thanks.
