### ISSUE TITLE
Project gone?

### ISSUE THREAD

**Issue by Sikatsu** [jolbol1/RandomCoordinatesV2#9]
Where did the project go too? I can't seem to download v2.0

**Comment by jolbol1** [comment]
Wow, I changed the name of the project to randomcoordinates-rtp and its changed the bukkit url.

Spigot is fine though.

Heres the Bukkit link: https://dev.bukkit.org/projects/randomcoordinates

(changed it back now)

**Comment by Sikatsu** [comment]
Oh nice, good news that you got your account back. Thanks for the update!
